import heroImage from "@assets/generated_images/african_savanna_with_elephants_at_golden_hour.png";
import zanzibarImage from "@assets/generated_images/pristine_zanzibar_beach_with_turquoise_water.png";
import kiliImage from "@assets/generated_images/mount_kilimanjaro_landscape.png";
import gorillaImage from "@assets/generated_images/mountain_gorilla_in_rainforest.png";

export const tours = [
  // Zanzibar Tours - Real Data from Technical Plan
  {
    id: "4-days-pre-christmas",
    title: "4 Days Zanzibar Pre-Christmas Holidays",
    category: "Beach",
    duration: "4 Days / 3 Nights",
    price: 930,
    image: zanzibarImage,
    description: "Focuses on beach relaxation with core excursions (Safari Blue, Stone Town, Sunset Cruise). All-inclusive packages at Paradise Beach Resort, Alladin Zanzibar, or Toa Hotel & Spa.",
    featured: true,
    location: "Zanzibar",
    mealPlan: "All-Inclusive",
  },
  {
    id: "blue-bay-resort",
    title: "Blue Bay Beach Resort & Spa",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 2415,
    image: zanzibarImage,
    description: "Beachfront stay with water sports, diving, cultural excursions, and core activities. Deluxe Garden View accommodation with half board.",
    featured: true,
    location: "Zanzibar",
    mealPlan: "Half Board",
  },
  {
    id: "royal-zanzibar",
    title: "Royal Zanzibar Beach Resort",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 3490,
    image: zanzibarImage,
    description: "Luxurious beach escape with snorkeling, beach sports, and core excursions. Superior Room with all-inclusive meals and premium amenities.",
    featured: true,
    location: "Zanzibar",
    mealPlan: "All-Inclusive",
  },
  {
    id: "zanzibar-bay-resort",
    title: "Zanzibar Bay Resort",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 1410,
    image: zanzibarImage,
    description: "Laid-back island stay near Chwaka National Park, with water sports, dhow excursions, and core activities. Luxury Room all-inclusive.",
    featured: false,
    location: "Zanzibar",
    mealPlan: "All-Inclusive",
  },
  {
    id: "sea-cliff-resort",
    title: "Sea Cliff Resort & Spa",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 1955,
    image: zanzibarImage,
    description: "Cliffside luxury with golf access, spa treatments, water activities, and core excursions. Garden View Room with half board.",
    featured: false,
    location: "Zanzibar",
    mealPlan: "Half Board",
  },
  {
    id: "diamonds-mapenzi-beach",
    title: "Diamonds Mapenzi Beach",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 2910,
    image: zanzibarImage,
    description: "Scenic shoreline stay with abundant water sports and core activities. Garden View Room with all-inclusive meals.",
    featured: false,
    location: "Zanzibar",
    mealPlan: "All-Inclusive",
  },
  {
    id: "the-mora-zanzibar",
    title: "The Mora Zanzibar",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 3910,
    image: zanzibarImage,
    description: "Luxury suites with private pools, water sports, and core excursions. Junior Suite Garden View with all-inclusive premium service.",
    featured: true,
    location: "Zanzibar",
    mealPlan: "All-Inclusive",
  },
  {
    id: "6-days-beach-holiday",
    title: "6 Days, 5 Nights Zanzibar Beach Holiday Experience",
    category: "Beach",
    duration: "6 Days / 5 Nights",
    price: 1705,
    image: zanzibarImage,
    description: "Extended beach holiday with swimming with turtles and core activities. Multiple accommodation options (The Mora, Royal Zanzibar, The Residence, Konokono Beach Resort).",
    featured: true,
    location: "Zanzibar",
    mealPlan: "Varies",
  },
  {
    id: "5-days-packages",
    title: "5 Days, 4 Nights Zanzibar Holiday Packages",
    category: "Beach",
    duration: "5 Days / 4 Nights",
    price: 1445,
    image: zanzibarImage,
    description: "Shorter version with core excursions. Choose from The Mora, Royal Zanzibar, The Residence, or Konokono Beach Resort.",
    featured: false,
    location: "Zanzibar",
    mealPlan: "Varies",
  },
  // Kenya Tours
  {
    id: "masai-mara-safari",
    title: "Masai Mara Migration Safari",
    category: "Safari",
    duration: "3 Days / 2 Nights",
    price: 1200,
    image: heroImage,
    description: "Witness the Great Migration in the world-famous Masai Mara. Includes game drives, luxury tented camp accommodation, and expert guides.",
    featured: true,
    location: "Kenya",
  },
  {
    id: "kilimanjaro-climb",
    title: "Kilimanjaro Machame Route",
    category: "Adventure",
    duration: "7 Days / 6 Nights",
    price: 2100,
    image: kiliImage,
    description: "Conquer the roof of Africa via the scenic Machame Route. Full support team, high success rate, and breathtaking views.",
    featured: true,
    location: "Kenya",
  },
  {
    id: "uganda-gorilla-trek",
    title: "Bwindi Gorilla Trekking",
    category: "Adventure",
    duration: "4 Days / 3 Nights",
    price: 1800,
    image: gorillaImage,
    description: "A once-in-a-lifetime encounter with mountain gorillas in Bwindi Impenetrable Forest. Permits included.",
    featured: false,
    location: "Uganda",
  }
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Traveler from UK",
    text: "The safari of a lifetime! Our guide was incredibly knowledgeable and we saw the Big 5 on our first day. Highly recommended!",
  },
  {
    id: 2,
    name: "Michael Chen",
    role: "Photographer",
    text: "As a photographer, the lighting and positioning were perfect. The team knew exactly where to go for the best shots.",
  },
  {
    id: 3,
    name: "Emma & David",
    role: "Honeymooners",
    text: "Zanzibar was pure magic. The resort recommendation was spot on. Thank you for making our honeymoon so special.",
  }
];
