import zanzibarBeachImage from "@assets/generated_images/pristine_zanzibar_beach_with_turquoise_water.png";
import heroImage from "@assets/generated_images/african_savanna_with_elephants_at_golden_hour.png";

export interface Location {
  id: string;
  name: string;
  slug: string;
  type: "Island" | "Beach" | "City" | "Nature" | "Historical" | "Archipelago" | "Atoll" | "Fishing Village" | "Coastal Village" | "Protected Forest" | "National Park" | "Game Reserve" | "Market" | "Historical Site" | "Lagoon" | "Sandbar";
  region: string;
  description: string;
  highlights: string[];
  activities?: string[];
  resorts?: string[];
  activity?: string;
  estimatedCost?: string;
  estimatedDuration?: string;
  relatedTours: string[];
  image?: string;
}

export interface LocationCategory {
  id: string;
  name: string;
  category: "Island" | "Beach" | "City" | "Nature" | "Historical";
  locations: Location[];
}

export interface Destination {
  id: string;
  name: string;
  slug: string;
  description: string;
  heroImage: string;
  heroSubtitle: string;
  categories: LocationCategory[];
  stats: Array<{ label: string; value: string }>;
  featured: boolean;
}

const sharedImage = zanzibarBeachImage;

const zanzibarCategories: LocationCategory[] = [
  {
    id: "islands_001",
    name: "Islands & Archipelagos",
    category: "Island",
    locations: [
      {
        id: "zanzibar-archipelago",
        name: "Zanzibar Archipelago",
        slug: "zanzibar-archipelago",
        type: "Archipelago",
        region: "Multiple",
        description: "The full island group including Unguja, Pemba, and surrounding atolls. Perfect base for multi-island exploration and water sports.",
        highlights: ["Multi-island tours", "Water sports", "Diverse marine life", "Cultural experiences"],
        relatedTours: ["4-days-pre-christmas", "6-days-beach-holiday", "5-days-packages"],
        image: sharedImage,
      },
      {
        id: "unguja-island",
        name: "Unguja Island (Main Zanzibar)",
        slug: "unguja-island",
        type: "Island",
        region: "Central",
        description: "The primary island hosting most tourism infrastructure. Home to Stone Town, Nungwi, and major beach resorts.",
        highlights: ["Stone Town UNESCO site", "Beach resorts", "Cultural experiences", "Infrastructure hub"],
        activities: ["Stone Town Tour", "Spice Tour", "Cultural exploration"],
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "mnemba-atoll",
        name: "Mnemba Island/Atoll",
        slug: "mnemba-atoll",
        type: "Atoll",
        region: "North",
        description: "Premier snorkeling and diving destination. Featured in Safari Blue excursions with dolphin watching and turtle encounters.",
        highlights: ["Snorkeling", "Dolphin watching", "Fishing", "Seafood lunch", "Marine biodiversity"],
        activities: ["Safari Blue Excursion", "Snorkeling", "Diving"],
        activity: "Safari Blue Excursion",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "prison-island",
        name: "Prison Island (Changuu Island)",
        slug: "prison-island",
        type: "Island",
        region: "West",
        description: "Historic island with boat access from Stone Town. Featured in optional excursions with turtle sanctuary.",
        highlights: ["Historic tours", "Turtle sanctuary", "Boat access", "Historical significance"],
        activity: "Prison Island Tour",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "pemba-island",
        name: "Pemba Island",
        slug: "pemba-island",
        type: "Island",
        region: "North",
        description: "Sister island north of Unguja, known for diving and less-touristy experiences.",
        highlights: ["Diving", "Authentic experiences", "Marine biodiversity", "Peaceful"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
    ],
  },
  {
    id: "beaches_001",
    name: "Beaches",
    category: "Beach",
    locations: [
      {
        id: "nungwi-beach",
        name: "Nungwi Beach",
        slug: "nungwi-beach",
        type: "Beach",
        region: "North Coast",
        description: "Popular northern beach known for calm waters, beach bars, and vibrant nightlife. Host to several resort packages.",
        highlights: ["Calm waters", "Beach bars", "Water sports", "Sunset views", "Resort infrastructure"],
        resorts: ["Royal Zanzibar", "The Mora Zanzibar", "Paradise Beach Resort"],
        activities: ["Swimming", "Snorkeling", "Diving", "Water sports"],
        relatedTours: ["royal-zanzibar", "the-mora", "4-days-pre-christmas"],
        image: sharedImage,
      },
      {
        id: "kendwa-beach",
        name: "Kendwa Beach",
        slug: "kendwa-beach",
        type: "Beach",
        region: "North Coast",
        description: "Pristine white sand beach adjacent to Nungwi with similar amenities but slightly quieter atmosphere.",
        highlights: ["White sand", "Clear waters", "Beach restaurants", "Less crowded"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "paje-beach",
        name: "Paje Beach",
        slug: "paje-beach",
        type: "Beach",
        region: "East Coast",
        description: "Scenic eastern beach with strong tide patterns, ideal for kitesurfing and water sports.",
        highlights: ["Kitesurfing", "Water sports", "Scenic views", "Beach restaurants"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "kiwengwa-beach",
        name: "Kiwengwa Beach",
        slug: "kiwengwa-beach",
        type: "Beach",
        region: "East Coast",
        description: "Long sandy beach on the east coast with various resort options and calm conditions.",
        highlights: ["Long beach", "Calm waters", "Resort infrastructure", "Water activities"],
        relatedTours: ["blue-bay-resort"],
        image: sharedImage,
      },
      {
        id: "marumbi-beach",
        name: "Marumbi Beach",
        slug: "marumbi-beach",
        type: "Beach",
        region: "East Coast",
        description: "Eastern coast beach known for tranquility and snorkeling opportunities.",
        highlights: ["Snorkeling", "Tranquil", "Marine life", "Beach walks"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "muyuni-beach",
        name: "Muyuni Beach",
        slug: "muyuni-beach",
        type: "Beach",
        region: "South/Southwest",
        description: "Less-developed beach offering authentic beach experiences and closer proximity to local communities.",
        highlights: ["Authentic experiences", "Local culture", "Quieter", "Less touristy"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "blue-lagoon",
        name: "Blue Lagoon",
        slug: "blue-lagoon",
        type: "Lagoon",
        region: "Central",
        description: "Picturesque lagoon area with crystal-clear turquoise waters, ideal for swimming and photography.",
        highlights: ["Crystal clear waters", "Photography", "Swimming", "Scenic"],
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "sandbank",
        name: "Sandbank",
        slug: "sandbank",
        type: "Sandbar",
        region: "Open Water",
        description: "Unique sandbank formation in open water, featured in optional excursions for picnicking and swimming with turtles.",
        highlights: ["Turtle encounters", "Picnicking", "Photography", "Unique experience"],
        activity: "Sandbank Picnic",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
    ],
  },
  {
    id: "cities_001",
    name: "Cities & Towns",
    category: "City",
    locations: [
      {
        id: "stone-town",
        name: "Stone Town",
        slug: "stone-town",
        type: "City",
        region: "West Coast",
        description: "UNESCO World Heritage Site and cultural heart of Zanzibar. Historic architecture, spice markets, and Arab heritage.",
        highlights: ["UNESCO site", "Historic architecture", "Darajani Market", "Spice tours", "Arab heritage"],
        activities: ["Stone Town Tour", "Spice Tour", "Market exploration", "Historical walking tours"],
        activity: "Stone Town Tour",
        estimatedDuration: "Full-day excursion",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "zanzibar-city",
        name: "Zanzibar City",
        slug: "zanzibar-city",
        type: "City",
        region: "West Coast",
        description: "Main urban center and capital of the Zanzibar Archipelago. Gateway for most visitors and home to Stone Town.",
        highlights: ["Main hub", "Airport access", "Markets", "Restaurants", "Accommodation variety"],
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "matemwe",
        name: "Matemwe",
        slug: "matemwe",
        type: "Fishing Village",
        region: "East Coast",
        description: "Traditional fishing village offering authentic local experiences and cultural immersion.",
        highlights: ["Fishing culture", "Local experiences", "Authentic", "Community interaction"],
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "nungwi-village",
        name: "Nungwi Village",
        slug: "nungwi-village",
        type: "Coastal Village",
        region: "North",
        description: "Charming northern village known for traditional dhow boat building, local culture, and water-based activities.",
        highlights: ["Dhow boats", "Local culture", "Village tours", "Authentic experiences"],
        activity: "Nungwi Village Tour",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
    ],
  },
  {
    id: "nature_001",
    name: "Natural & Protected Areas",
    category: "Nature",
    locations: [
      {
        id: "jozani-forest",
        name: "Jozani Forest",
        slug: "jozani-forest",
        type: "Protected Forest",
        region: "Central",
        description: "Only remaining natural forest on Zanzibar. Home to endemic red colobus monkeys, exotic birds, and diverse flora.",
        highlights: ["Red colobus monkeys", "Exotic birds", "Nature trails", "Endemic species"],
        activity: "Jozani Forest Tour",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "chwaka-national-park",
        name: "Chwaka National Park",
        slug: "chwaka-national-park",
        type: "National Park",
        region: "Central",
        description: "Marine and terrestrial protected area near Zanzibar Bay Resort. Features wetlands, mangroves, and birdwatching.",
        highlights: ["Mangroves", "Birdwatching", "Wetlands", "Marine life"],
        relatedTours: ["zanzibar-bay-resort"],
        image: sharedImage,
      },
      {
        id: "selous-game-reserve",
        name: "Selous Game Reserve",
        slug: "selous-game-reserve",
        type: "Game Reserve",
        region: "Mainland Tanzania",
        description: "Large safari reserve on mainland Tanzania, accessible via day excursion from Zanzibar.",
        highlights: ["Safari", "Wildlife", "Big Five", "Day trip option"],
        activity: "Day Safari to Selous",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "mikumi-national-park",
        name: "Mikumi National Park",
        slug: "mikumi-national-park",
        type: "National Park",
        region: "Mainland Tanzania",
        description: "Another mainland safari option with diverse wildlife and scenic landscapes.",
        highlights: ["Safari", "Wildlife", "Scenic", "Day trip option"],
        activity: "Day Safari to Mikumi",
        estimatedCost: "Optional add-on",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
    ],
  },
  {
    id: "historical_001",
    name: "Markets & Historical Sites",
    category: "Historical",
    locations: [
      {
        id: "darajani-market",
        name: "Darajani Market",
        slug: "darajani-market",
        type: "Market",
        region: "Stone Town",
        description: "Historic spice market in Stone Town. Vibrant, colorful marketplace showcasing Zanzibar's spice trade heritage.",
        highlights: ["Spice market", "Local produce", "Cultural experience", "Photography"],
        activity: "Market exploration",
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
      {
        id: "slave-trade-caves",
        name: "Slave Trade Caves",
        slug: "slave-trade-caves",
        type: "Historical Site",
        region: "Stone Town",
        description: "Historic caves related to Zanzibar's slave trade history. Educational and culturally significant.",
        highlights: ["Historical significance", "Cultural education", "Guided tours", "Deep history"],
        activity: "Historical tour",
        relatedTours: ["custom-tours"],
        image: sharedImage,
      },
      {
        id: "palace-stone-town",
        name: "Palace",
        slug: "palace-stone-town",
        type: "Historical Site",
        region: "Stone Town",
        description: "Historic palace structure in Stone Town representing Sultanate heritage.",
        highlights: ["Sultanate architecture", "Historical tours", "Cultural significance"],
        relatedTours: ["all-tours"],
        image: sharedImage,
      },
    ],
  },
];

const kenyaCategories: LocationCategory[] = [
  {
    id: "national-parks_001",
    name: "National Parks & Reserves",
    category: "Nature",
    locations: [
      {
        id: "masai-mara",
        name: "Masai Mara National Reserve",
        slug: "masai-mara",
        type: "National Park",
        region: "Southwest Kenya",
        description: "World-famous safari destination known for the Great Migration. Home to the Big Five and diverse wildlife viewing opportunities.",
        highlights: ["Great Migration", "Big Five", "Scenic landscapes", "Game drives"],
        activities: ["Safari Game Drive", "Wildlife Photography", "Guided Tours"],
        activity: "Safari Game Drive",
        relatedTours: ["masai-mara-safari"],
        image: heroImage,
      },
      {
        id: "amboseli-national-park",
        name: "Amboseli National Park",
        slug: "amboseli-national-park",
        type: "National Park",
        region: "Southeast Kenya",
        description: "Famous for its elephant herds and stunning views of Mount Kilimanjaro. Unique ecosystem with lakes and wildlife.",
        highlights: ["Elephant herds", "Mount Kilimanjaro views", "Birdwatching", "Photography"],
        activities: ["Game drives", "Wildlife viewing", "Photography tours"],
        relatedTours: ["masai-mara-safari"],
        image: heroImage,
      },
      {
        id: "tsavo-national-park",
        name: "Tsavo National Park",
        slug: "tsavo-national-park",
        type: "National Park",
        region: "Southeast Kenya",
        description: "Kenya's largest national park split into East and West. Known for its red soil and diverse wildlife populations.",
        highlights: ["Red elephants", "Vast landscapes", "Wildlife diversity", "Camping"],
        activities: ["Safari drives", "Hiking", "Wildlife viewing"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
      {
        id: "samburu-national-reserve",
        name: "Samburu National Reserve",
        slug: "samburu-national-reserve",
        type: "National Park",
        region: "North Kenya",
        description: "Remote reserve known for unique wildlife including grevy's zebra, reticulated giraffe, and Somali ostrich.",
        highlights: ["Unique species", "Dramatic scenery", "Remote location", "Cultural experiences"],
        activities: ["Safari drives", "Cultural tours", "Photography"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
    ],
  },
  {
    id: "mountains_001",
    name: "Mountains & Highlands",
    category: "Nature",
    locations: [
      {
        id: "mount-kenya",
        name: "Mount Kenya",
        slug: "mount-kenya",
        type: "National Park",
        region: "Central Kenya",
        description: "Africa's second-highest peak offering trekking routes for all levels. Stunning Alpine scenery and diverse ecosystems.",
        highlights: ["Mountain trekking", "Alpine scenery", "Wildlife viewing", "Photography"],
        activities: ["Trekking", "Climbing", "Guided hikes"],
        activity: "Mountain Trekking",
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
      {
        id: "aberdare-range",
        name: "Aberdare Range",
        slug: "aberdare-range",
        type: "National Park",
        region: "Central Kenya",
        description: "Misty highlands with forest trails, waterfalls, and opportunities to spot elusive wildlife like black rhinoceros.",
        highlights: ["Forest hikes", "Waterfalls", "Wildlife viewing", "Mountain scenery"],
        activities: ["Hiking", "Forest walks", "Wildlife tours"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
    ],
  },
  {
    id: "beaches-lakes_001",
    name: "Beaches & Lakes",
    category: "Beach",
    locations: [
      {
        id: "mombasa-beach",
        name: "Mombasa Beach",
        slug: "mombasa-beach",
        type: "Beach",
        region: "Coastal Kenya",
        description: "Historic coastal city with pristine beaches, coral reefs, and water sports. Gateway to Kenya's Indian Ocean.",
        highlights: ["White sand beaches", "Coral reefs", "Water sports", "Historic sites"],
        activities: ["Swimming", "Snorkeling", "Diving", "Beach relaxation"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
      {
        id: "diani-beach",
        name: "Diani Beach",
        slug: "diani-beach",
        type: "Beach",
        region: "South Coast",
        description: "Popular beach resort destination with clear turquoise waters, palm-fringed shores, and luxury resorts.",
        highlights: ["Clear waters", "Beach resorts", "Water sports", "Sunset views"],
        activities: ["Swimming", "Kiteboarding", "Beach bars", "Relaxation"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
      {
        id: "lake-nakuru",
        name: "Lake Nakuru",
        slug: "lake-nakuru",
        type: "Lagoon",
        region: "Central Kenya",
        description: "Crater lake known for its flamingo population and rhinoceros sanctuary. Part of the Great Rift Valley.",
        highlights: ["Flamingos", "Rhinoceros", "Lake views", "Birdwatching"],
        activities: ["Wildlife viewing", "Photography", "Birdwatching tours"],
        relatedTours: ["masai-mara-safari"],
        image: heroImage,
      },
    ],
  },
  {
    id: "cities_001",
    name: "Cities & Towns",
    category: "City",
    locations: [
      {
        id: "nairobi",
        name: "Nairobi",
        slug: "nairobi",
        type: "City",
        region: "Central Kenya",
        description: "Kenya's vibrant capital city. Hub for tours, shopping, restaurants, and museums. Gateway to East African safaris.",
        highlights: ["Museums", "Markets", "Restaurants", "Shopping"],
        activities: ["City tours", "Museum visits", "Shopping"],
        relatedTours: ["all-tours"],
        image: heroImage,
      },
      {
        id: "mombasa",
        name: "Mombasa",
        slug: "mombasa",
        type: "City",
        region: "Coastal Kenya",
        description: "Historic coastal city with swahili architecture, markets, and cultural heritage. Entry point to coastal attractions.",
        highlights: ["Swahili architecture", "Historic sites", "Local markets", "Coastal culture"],
        activities: ["Walking tours", "Cultural experiences", "Beach access"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
    ],
  },
  {
    id: "cultural_001",
    name: "Cultural & Historical Sites",
    category: "Historical",
    locations: [
      {
        id: "maasai-villages",
        name: "Maasai Villages",
        slug: "maasai-villages",
        type: "Historical Site",
        region: "South Kenya",
        description: "Experience authentic Maasai culture, traditions, and hospitality. Learn about their unique way of life.",
        highlights: ["Cultural immersion", "Traditional dances", "Local crafts", "Educational"],
        activity: "Maasai Cultural Tour",
        relatedTours: ["masai-mara-safari"],
        image: heroImage,
      },
      {
        id: "lamu-island",
        name: "Lamu Island",
        slug: "lamu-island",
        type: "Historical Site",
        region: "North Coast",
        description: "UNESCO World Heritage Site with well-preserved Swahili architecture, museums, and rich cultural heritage.",
        highlights: ["UNESCO site", "Historic architecture", "Local culture", "Beaches"],
        activities: ["Island exploration", "Cultural tours", "Water sports"],
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
      {
        id: "karen-blixen-museum",
        name: "Karen Blixen Museum",
        slug: "karen-blixen-museum",
        type: "Historical Site",
        region: "Nairobi",
        description: "Historic home of the author of 'Out of Africa'. Now a museum showcasing colonial Kenya heritage.",
        highlights: ["Colonial history", "Literary connections", "Historic house", "Gardens"],
        activity: "Museum Tour",
        relatedTours: ["custom-tours"],
        image: heroImage,
      },
    ],
  },
];

export const destinations: Destination[] = [
  {
    id: "zanzibar",
    name: "Zanzibar",
    slug: "zanzibar",
    description: "Pristine beaches, historic Stone Town, and island adventures in Tanzania's paradise.",
    heroImage: zanzibarBeachImage,
    heroSubtitle: "Explore pristine beaches, cultural heritage, and island adventures across Zanzibar's most beautiful destinations",
    categories: zanzibarCategories,
    stats: [
      { label: "Destinations", value: "20+" },
      { label: "Resort Packages", value: "9" },
      { label: "Activities", value: "15+" },
      { label: "Average Rating", value: "4.8★" },
    ],
    featured: true,
  },
  {
    id: "kenya",
    name: "Kenya",
    slug: "kenya",
    description: "Epic safari experiences, diverse wildlife, and stunning landscapes across Africa's premier destination.",
    heroImage: heroImage,
    heroSubtitle: "Discover world-class safaris, from Masai Mara's Great Migration to Mount Kenya's Alpine peaks",
    categories: kenyaCategories,
    stats: [
      { label: "Destinations", value: "15+" },
      { label: "Safari Packages", value: "8+" },
      { label: "Activities", value: "20+" },
      { label: "Average Rating", value: "4.9★" },
    ],
    featured: true,
  }
];

// Helper functions for scalability
export const getAllDestinations = () => destinations;

export const getDestinationBySlug = (slug: string) => 
  destinations.find(d => d.slug === slug);

export const getFeaturedDestinations = () =>
  destinations.filter(d => d.featured);
